FROM lsiobase/alpine:3.12 as builder
# set label
LABEL maintainer="NG6"
ARG S6_VER=2.1.0.2
WORKDIR /downloads
COPY ReleaseTag  /downloads
# download bilibili-helper
RUN apk add --no-cache unzip \
&&	BHV=$(cat ReleaseTag | head -n1) \
&&	wget --no-check-certificate https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/releases/download/v${BHV}/BILIBILI-HELPER-${BHV}-jar-with-dependencies.jar \
&&	unzip BILIBILI-HELPER-v${BHV}.zip \
&&	mv BILIBILI-HELPER-v${BHV}.jar BILIBILI-HELPER.jar
# download s6-overlay
RUN	if [ "$(uname -m)" = "x86_64" ];then s6_arch=amd64;elif [ "$(uname -m)" = "aarch64" ];then s6_arch=aarch64;elif [ "$(uname -m)" = "armv7l" ];then s6_arch=arm; fi  \
&&  wget --no-check-certificate https://github.com/just-containers/s6-overlay/releases/download/v${S6_VER}/s6-overlay-${s6_arch}.tar.gz  \
&&	mkdir ./s6-overlay \
&&  tar -xvzf s6-overlay-${s6_arch}.tar.gz -C ./s6-overlay	

# bilibili-helper
FROM arm32v7/openjdk:8-jdk-slim
# set label
LABEL maintainer="NG6"
ENV TZ=Asia/Shanghai TASK=1d CRON=false \
    CUSP=false DEDEUSERID=1 SESSDATA=2 BILI_JCT=3 \
    PUID=1026 PGID=100
# copy files
COPY root/ /
COPY --from=builder /downloads/BILIBILI-HELPER.jar  /app/BILIBILI-HELPER.jar
COPY --from=builder /downloads/s6-overlay/  /
COPY --from=builder /downloads/config.json  /app-conf/config.json
# create abc user
RUN apt -y update && apt -y install tzdata cron \
&&  chmod +x /app/BILIBILI-HELPER.jar \
&&  useradd -u 1000 -U -d /config -s /bin/false abc \
&&  usermod -G users abc  \
&&  echo "**** cleanup ****" \
&&  apt-get clean \
&&  rm -rf \
	/tmp/* \
	/var/lib/apt/lists/* \
	/var/tmp/*


WORKDIR /app
# volume
VOLUME [ "/config" ]

ENTRYPOINT [ "/init" ]
