#!/usr/bin/with-contenv bash

# 启动定时任务,默认每天执行一次
# 启动bilbili-helper

if [ "${CRON}" = true ]
then
    crontab /etc/cron.d/bh-crontab
    echo "===========检查CRON定时任务==========="
    cat /etc/cron.d/bh-crontab
    echo "===========已启动定时任务==========="
    echo "===========刚启动容器时为上次的运行日志，定时任务完成后日志会刷新==========="
    cron && tail -f /config/bilbili-helper.log
fi

cd /app && java -jar /app/BILIBILI-HELPER.jar ${DEDEUSERID} ${SESSDATA} ${BILI_JCT} ${SERVERPUSHKEY} | s6-setuidgid abc tee -a /config/bilbili-helper.log

echo -e "==================$(date +"%Y/%m/%d %H:%M:%S")==================" | s6-setuidgid abc tee -a /config/bilbili-helper.log
echo -e "==========今天已签到完毕，下次签到时间为${TASK}后===========" | s6-setuidgid abc tee -a /config/bilbili-helper.log
sleep ${TASK}
