#!/usr/bin/with-contenv bash

# copy config.json
if [ ! -e /config/config.json ]
then
  cp /app-conf/config.json /config/config.json
fi

# 创建运行日志文件
if [ ! -e /config/bilibili-helper.log ]
then
  touch /config/bilibili-helper.log
fi

# 创建crontab
if [ ! -e /config/bh-crontab ]
then
  cp /app-conf/bh-crontab /config/bh-crontab
fi

rm -f /etc/cron.d/bh-crontab

if [ "${CRON}" = true ] || [ "${CRON}" = random ]
then
  cp /config/bh-crontab /etc/cron.d/bh-crontab
  chmod 0644 /etc/cron.d/bh-crontab
fi


# permissions
chmod +x /app-conf/bh-run.sh
chmod +x /app-conf/random-bh.sh
chown -R abc:abc /config
