#!/usr/bin/with-contenv bash

# download config.json
if [ "${CUSP}" = true ] && [ ! -e /config/config.json ]
then
  rm -f /app/config.json
  cp /app-conf/config.json /config/config.json
  cp /config/config.json /app/config.json
  chown -R root:root /app/config.json
elif [ "${CUSP}" = true ] && [ -e /config/config.json ]
then
  rm -f /app/config.json
  cp /config/config.json /app/config.json
  chown -R root:root /app/config.json
elif [[ "${CUSP}" = false ]]
then
  rm -f /config/config.json
  rm -f /app/config.json
fi

if [[ ! -e /config/bilbili-helper.log ]]
then
  touch /config/bilbili-helper.log
fi

# permissions
chown -R abc:abc \
    /config
