#!/usr/bin/with-contenv bash

# download config.json
if [ "${CUSP}" = true ] && [ ! -e /bilbili-helper/config.json ]
then
  wget -P /bilbili-helper https://cdn.jsdelivr.net/gh/JunzhouLiu/BILIBILI-HELPER@main/src/main/resources/config.json
elif [ "${CUSP}" = false ] && [ -e /bilbili-helper/config.json ]
then
  rm -f /bilbili-helper/config.json
fi

# permissions
chown -R abc:abc \
    /bilbili-helper
  
chmod a+x \
  /bilbili-helper/BILIBILI-HELPER.jar
